name: visual-sound
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.7.0
  - annotated-types=0.6.0
  - archspec=0.2.3
  - boltons=24.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - conda=25.3.1
  - conda-anaconda-telemetry=0.1.2
  - conda-anaconda-tos=0.1.3
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cpp-expected=1.1.0
  - cryptography=44.0.1
  - distro=1.9.0
  - expat=2.7.1
  - fmt=9.1.0
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.7.7
  - libcurl=8.12.1
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - mdurl=0.1.0
  - menuinst=2.2.0
  - ncurses=6.4
  - nlohmann_json=3.11.2
  - openssl=3.0.16
  - packaging=24.2
  - pcre2=10.42
  - pip=25.0
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.9
  - python_abi=3.9
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - rich=13.9.4
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - setuptools=78.1.1
  - simdjson=3.10.1
  - spdlog=1.11.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.67.1
  - truststore=0.10.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - nvidia-ml-py==12.575.51
      - nvitop==1.5.1
      - psutil==7.0.0

